### ISSUE TITLE
Alpha is not consistent

### ISSUE THREAD

**Issue by misterff1** [alecxvs/UTChat#24] opened 2015-06-03 15:16 UTC
![image4](https://cloud.githubusercontent.com/assets/3277023/7963641/08c65888-0a14-11e5-9fbc-21c25d742836.png)
As you can see on the image above, the alpha differs per message. This looks kinda messy and the alpha is sometimes too low to actually be readable. 

![image5](https://cloud.githubusercontent.com/assets/3277023/7963658/29192e1c-0a14-11e5-9f17-33e233e10ee7.png)

In this second image you can see (if you look really closely to the lowerleft corner) that when hiding the chat, it also doesn't fully hide it all the time. I think this is just the same issue.

**Comment by alecxvs** [comment] 2015-06-03 15:42
Does this happen all the time or when you have a low frame rate? I have a feeling that this is related to the messages stacking.

**Comment by misterff1** [comment] 2015-06-03 16:26
lol I always have a low framerate :)    I asked someone with a high framerate and he does not seem to have that issue indeed. However, he did have message stacking before (not lately though)

Update: He did change to a newer GPU, so that might have stabilized framerate more

**Comment by alecxvs** [comment] 2015-06-03 18:46
Duplicate of #20

**Closed as completed by alecxvs** 2015-06-03 18:46 UTC
Labels: duplicate
